version: '3.3'

services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=WoodenFurnitureStore
      - MYSQL_ROOT_PASSWORD=Thanhliem2612.
    ports:
      - '3307:3306'
    networks:
      - my_network

  be-nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DEV_DB_HOST=database-mysql
      - DEV_DB_PORT=3306
      - DEV_DB_NAME=WoodenFurnitureStore
      - URL_FE_CORS=http://localhost
      - DEV_DB_USERNAME=root
    ports:
      - '8080:8080'
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
